### ISSUE TITLE
PLCRFactory fails to deploy - can't deploy TCR

### ISSUE THREAD

**Issue by drewstone** [skmgoldin/tcr#75]
Running node 8.11.1, trying to deploy to any test network and receiving the following error.

```
Running migration: 3_optional_plcr_factory.js
  Linking DLL to PLCRFactory
  Linking AttributeStore to PLCRFactory
  Deploying PLCRFactory...
  ... 0x69052b83a484f82fa7444b580ac23061dc9d0caa29cfce34e35bb9abb0886eda
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/Users/drewstone/src/eth/cw/tcr/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /Users/drewstone/src/eth/cw/tcr/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /Users/drewstone/src/eth/cw/tcr/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /Users/drewstone/src/eth/cw/tcr/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /Users/drewstone/src/eth/cw/tcr/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at /Users/drewstone/src/eth/cw/tcr/node_modules/web3-provider-engine/index.js:152:9
    at /Users/drewstone/src/eth/cw/tcr/node_modules/async/internal/once.js:12:16
    at replenish (/Users/drewstone/src/eth/cw/tcr/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/drewstone/src/eth/cw/tcr/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/drewstone/src/eth/cw/tcr/node_modules/async/eachLimit.js:43:36)
    at /Users/drewstone/src/eth/cw/tcr/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/drewstone/src/eth/cw/tcr/node_modules/web3-provider-engine/index.js:127:5)
    at /Users/drewstone/src/eth/cw/tcr/node_modules/web3-provider-engine/subproviders/provider.js:20:5
    at XMLHttpRequest.request.onreadystatechange (/Users/drewstone/src/eth/cw/tcr/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/drewstone/src/eth/cw/tcr/node_modules/web3/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/drewstone/src/eth/cw/tcr/node_modules/web3/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/drewstone/src/eth/cw/tcr/node_modules/web3/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/drewstone/src/eth/cw/tcr/node_modules/web3/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by drewstone** [comment]
@skmgoldin Any ideas why the PLCRFactory won't deploy to ropsten or rinkeby? It doesn't appear to be a gas issue.

**Comment by kangarang** [comment]
hi @drewstone , how'd you resolve this issue? did you have to increase the gas in `truffle.js`?

**Comment by drewstone** [comment]
@kangarang use a gas limit of `6721975` for Rinkeby.

**Comment by LiorRabin** [comment]
Hey @drewstone, I've managed to deploy to Ropsten with gas limit `6721975` as well

**Comment by skybach** [comment]
@LiorRabin how did you deploy to ropsten with that high a gas limit?

**Comment by LiorRabin** [comment]
@skybach you can see here https://ropsten.etherscan.io/blocks that gas limit is around 8M now

**Comment by skybach** [comment]
why did truffle complain when i set anything greater than 4.7M gas limit?

**Comment by skybach** [comment]
ok...think i was using geth 1.8.12 which somehow capped the returned gas limit field to 4M.
geth 1.8.18 shows the correct limit that is on the blockchain.
